apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: eu-west-1
    secureJsonData:
      accessKey: "${CLOUDWATCH_ACCESS_KEY}"
      secretKey: "${CLOUDWATCH_SECRET_KEY}"

  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    jsonData:
      subscriptionId: "${AZURE_SUBSCRIPTION_ID}"
      tenantId: "${AZURE_TENANT_ID}"
      clientId: "${AZURE_CLIENT_ID}"
      cloudName: azuremonitor
    secureJsonData:
      clientSecret: "${AZURE_CLIENT_SECRET}"

  - name: Prometheus-AWS
    type: prometheus
    url: http://${AWS_EC2_IP}:9100
    access: proxy
    isDefault: false

  - name: Prometheus-Azure
    type: prometheus
    url: http://${AZURE_VM_IP}:9100
    access: proxy
    isDefault: false